POST http://localhost:8000/createurl
content-type: application/json

{
    "shortUrl": "hellog",
    "url": "https://google.com"
}

###
GET http://localhost:8000/hellog

###
GET http://localhost:8000/shorturl/all